
function ONas() {
    return <div className="onas">
        <p className="naglowek"><b>Kim jesteśmy, jak powstaliśmy?</b></p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ut blandit nisi. Aliquam luctus volutpat ipsum, at tristique eros interdum eu. Maecenas faucibus libero urna, ut tincidunt dui tristique sit amet. Vestibulum vitae vehicula ligula, eget ornare libero. Aenean at lectus aliquam, placerat augue at, dignissim neque. Phasellus a gravida massa. Curabitur at justo scelerisque nulla vulputate sodales ac a lacus. Morbi fringilla non nisl et gravida. Phasellus non magna a ante gravida malesuada sed non leo. Nunc feugiat neque nec ligula posuere pulvinar. Morbi sit amet nibh ligula.</p>
        <p>Cras ultrices luctus ex sed pellentesque. Nullam facilisis venenatis consectetur. Quisque fermentum tortor ac est blandit, nec dignissim magna aliquam. Donec turpis ligula, feugiat at dui a, ullamcorper egestas libero. Maecenas mollis sed dui id feugiat. Vestibulum nec felis metus. Phasellus sapien turpis, tincidunt in nibh a, lacinia elementum sem. Proin est ex, aliquet in felis a, sollicitudin fermentum turpis. Vestibulum non eleifend arcu. Mauris ac lacus varius, laoreet magna eu, efficitur ante.</p>
        <p>Nulla facilisi. Morbi dui neque, dapibus at ullamcorper quis, dignissim vel tellus. Sed aliquam metus ligula, nec consectetur eros tristique vel. Suspendisse sit amet dui ac nisi semper hendrerit. Donec eget ligula et elit consequat laoreet id quis neque. Etiam pellentesque lectus eget sem dictum congue. Donec fermentum odio vitae placerat semper. Nam pharetra suscipit pulvinar. Nullam interdum ullamcorper sagittis. In eget enim tempor quam mattis ultricies. In hac habitasse platea dictumst. Donec vel eros vitae justo pretium lacinia at a turpis. Nulla vitae purus id felis dictum tincidunt. Mauris non diam fringilla, congue elit vel, convallis ipsum.</p>
        <p>Suspendisse tristique nunc vel imperdiet bibendum. Vestibulum eu sapien sit amet ipsum volutpat pretium. Fusce a ante id sapien fermentum vulputate ut sit amet diam. Curabitur venenatis vestibulum gravida. Maecenas turpis lectus, accumsan sed nisl congue, bibendum efficitur eros. Cras quis lobortis sapien. Nullam id euismod arcu, at mollis odio. Praesent ultrices lectus eget malesuada porta. Etiam aliquam consectetur dui at dignissim. Sed id nunc vitae eros pretium sollicitudin et vestibulum felis. Sed ornare mi a leo facilisis ultrices. Maecenas et augue metus. Praesent sed magna accumsan, rutrum nunc nec, semper purus. Etiam sit amet felis diam. Proin nec mollis nisi, at elementum neque. Vestibulum ac ullamcorper massa, a lacinia arcu.</p>
        <p>Ut blandit ante tincidunt orci ultricies gravida. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum ut metus convallis nisi elementum sagittis. Mauris gravida tortor ut orci tincidunt, eu aliquet elit ullamcorper. Praesent at urna ut mi ornare tristique. Proin nunc ligula, ullamcorper quis posuere a, pulvinar et mi. Curabitur sodales sed nibh vel accumsan. Duis at ullamcorper mi. Curabitur pretium quis ipsum eget suscipit. Aenean blandit lacus ac tempor dignissim. Praesent dapibus, quam eu egestas scelerisque, urna ex cursus eros, quis varius elit metus sed ex. Aliquam quis nunc felis. Morbi sollicitudin nisl ante, vitae viverra urna vestibulum quis. Vivamus condimentum, lectus ut rutrum fringilla, lorem velit luctus ipsum, bibendum tincidunt velit erat sit amet mauris. Curabitur mauris enim, mollis in venenatis eu, feugiat eget eros. Donec at fringilla orci.</p>
    </div>;
}

export default ONas;
